# Generated by Django 3.2.8 on 2021-10-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Osnumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('nome', models.CharField(max_length=60)),
                ('contato', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[('V', 'Vendedor'), ('O', 'Operador')], max_length=1)),
            ],
            bases=('home.base',),
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=10)),
                ('media', models.IntegerField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('vendedor', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('numeos', models.IntegerField()),
                ('placa', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('orcamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_orcamento', models.DateTimeField(blank=True)),
                ('data_aprovacao', models.DateTimeField(blank=True)),
                ('data_entrega', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('0', 'inciada'), ('1', 'Andamento'), ('2', 'Aguardando'), ('3', 'Finalizada')], max_length=1)),
                ('prioridade', models.IntegerField()),
                ('lateral', models.IntegerField()),
                ('defletor', models.IntegerField()),
                ('conexoes', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('bracadeira', models.IntegerField()),
                ('tampa', models.IntegerField()),
                ('coxin', models.IntegerField()),
                ('mangueira', models.IntegerField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.funcionario')),
            ],
            bases=('home.base',),
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('fase', models.CharField(max_length=30)),
                ('media', models.IntegerField()),
                ('inicio', models.DateTimeField(blank=True)),
                ('fim', models.DateTimeField(blank=True)),
                ('decorrido', models.IntegerField()),
                ('limpesa', models.CharField(max_length=4)),
                ('concerto', models.CharField(max_length=4)),
                ('caixa_sup', models.CharField(max_length=4)),
                ('caixa_inf', models.CharField(max_length=4)),
                ('elemento', models.CharField(max_length=4)),
                ('bocal', models.CharField(max_length=4)),
                ('rad_novo', models.CharField(max_length=4)),
                ('mostrar', models.CharField(choices=[('1', 'Sim'), ('0', 'Não'), ('2', 'Ativo')], max_length=1)),
                ('id_ordem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.ordem')),
            ],
            bases=('home.base',),
        ),
    ]
