# Generated by Django 3.2.8 on 2021-10-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tempo_etapa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordem',
            old_name='numeos',
            new_name='numeros',
        ),
    ]
