# Generated by Django 3.2.8 on 2021-10-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_ordem_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.modelo'),
        ),
    ]
