# Generated by Django 3.2.8 on 2021-10-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_ordem_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='tipo',
            field=models.CharField(choices=[('N', 'Nova'), ('R', 'Retrabalho'), ('2', 'Outro')], max_length=1),
        ),
    ]
