# Generated by Django 3.2.8 on 2021-10-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_ordem_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='bocal',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='caixa_inf',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='caixa_sup',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='concerto',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='elemento',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='limpesa',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='rad_novo',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1),
        ),
    ]
