# Generated by Django 3.2.8 on 2021-10-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_concerto_etapa_conserto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='orcamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
