# Generated by Django 3.2.8 on 2021-10-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_ordem_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='orcamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
