# Generated by Django 3.2.8 on 2021-10-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_ordem_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='data_aprovacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_entrega',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_orcamento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
