# Generated by Django 3.2.8 on 2021-10-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_etapa_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='bocal',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='caixa_inf',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='caixa_sup',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='conserto',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='elemento',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='limpesa',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='mostrar',
            field=models.CharField(choices=[('1', 'Sim'), ('0', 'Não'), ('2', 'Ativo')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='rad_novo',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
    ]
