# Generated by Django 3.2.8 on 2021-10-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211008_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='status',
            field=models.CharField(choices=[('0', 'Aberto'), ('1', 'Executando'), ('2', 'Concluindo')], default='0', max_length=1),
        ),
    ]
