# Generated by Django 3.2.8 on 2021-10-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_etapa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='decorrido',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='fim',
            field=models.DateTimeField(blank=True, default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='inicio',
            field=models.DateTimeField(blank=True, default='00:00:00'),
        ),
    ]
