# Generated by Django 3.2.8 on 2021-10-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211011_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
