# Generated by Django 3.2.8 on 2021-10-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211011_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='status',
            field=models.CharField(choices=[('0', 'Aberto'), ('1', 'Executando'), ('2', 'Retomar'), ('3', 'Final')], default='0', max_length=1),
        ),
    ]
