# Generated by Django 3.2.8 on 2021-10-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_ordem_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='numeros',
            field=models.IntegerField(default=0),
        ),
    ]
