# Generated by Django 3.2.8 on 2021-10-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_ordem_numeros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='bracadeira',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='conexoes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='coxin',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='defletor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='lateral',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='mangueira',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='obs',
            field=models.CharField(default='Nada', max_length=200),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='tampa',
            field=models.IntegerField(default=1),
        ),
    ]
