# Generated by Django 3.2.8 on 2021-10-17 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20211016_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='operador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.funcionario'),
        ),
    ]
