# Generated by Django 3.2.8 on 2021-10-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_ordem_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='prioridade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='status',
            field=models.CharField(choices=[('0', 'inciada'), ('1', 'Andamento'), ('2', 'Aguardando'), ('3', 'Finalizada')], default='0', max_length=1),
        ),
    ]
