# Generated by Django 3.2.8 on 2021-10-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20211021_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='colmeia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='bracadeira',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='conexoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='coxin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='defletor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='lateral',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='mangueira',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='tampa',
            field=models.IntegerField(default=0),
        ),
    ]
