# Generated by Django 4.1.2 on 2022-11-26 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0029_auto_20220620_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ['modelo']},
        ),
        migrations.AlterModelOptions(
            name='ordem',
            options={'verbose_name_plural': 'Ordens'},
        ),
        migrations.AlterModelOptions(
            name='osnumero',
            options={'verbose_name_plural': 'OS Números'},
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='operador',
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='placa',
        ),
        migrations.AddField(
            model_name='etapa',
            name='obs_etapa',
            field=models.TextField(default='Nada'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.funcionario'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='os_ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etapa',
            name='parada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapa',
            name='retomada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordem',
            name='obs_ordem',
            field=models.TextField(default='Nada'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='id_ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ordem'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.modelo'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tempo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.modelo'),
        ),
    ]
