# Generated by Django 4.1.2 on 2022-11-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_etapa_id_ordem_alter_etapa_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='parado',
            field=models.IntegerField(default=0),
        ),
    ]
