# Generated by Django 4.1.2 on 2022-11-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_etapa_parado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='parado',
        ),
    ]
