# Generated by Django 4.1.2 on 2022-11-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_etapa_parado'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='parado',
            field=models.IntegerField(default=0),
        ),
    ]
