# Generated by Django 4.1.2 on 2022-12-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_etapa_parado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterField(
            model_name='etapa',
            name='operador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.funcionario'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='status',
            field=models.CharField(choices=[('0', 'Aberto'), ('1', 'Executando'), ('6', 'Aguardando'), ('8', 'Parado'), ('2', 'Retomar'), ('3', 'Final')], default='0', max_length=1),
        ),
    ]
