# Generated by Django 4.1.4 on 2023-03-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_funcionario_options_alter_etapa_operador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='operador',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='home.funcionario'),
        ),
    ]
