# Generated by Django 4.1.4 on 2023-05-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_etapa_operador'),
    ]

    operations = [
        migrations.CreateModel(
            name='motivoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mParada', models.CharField(max_length=150)),
            ],
        ),
    ]
