# Generated by Django 4.1.4 on 2023-05-30 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_motivoparada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivoparada',
            options={'ordering': ['mParada'], 'verbose_name': 'Motivo de Parada'},
        ),
        migrations.AddField(
            model_name='motivoparada',
            name='almoco',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='motivoparada',
            name='fim_de_turno',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='motivoparada',
            name='id_etapa',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to='home.etapa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motivoparada',
            name='id_ordem',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to='home.ordem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motivoparada',
            name='outros',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='motivoparada',
            name='quantidadeParadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motivoparada',
            name='setup',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='motivoparada',
            name='mParada',
            field=models.CharField(max_length=150, verbose_name='Motivo de Parada'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='numeros',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='status',
            field=models.CharField(choices=[('0', 'inciada'), ('1', 'Andamento'), ('2', 'Aguardando'), ('3', 'Finalizada'), ('4', 'Pendente de Abertura')], default='4', max_length=1),
        ),
    ]
