# Generated by Django 4.1.4 on 2023-06-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_motivoparada_options_motivoparada_almoco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='almoco',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='etapa',
            name='fim_de_turno',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='etapa',
            name='outros',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='etapa',
            name='quantidadeParadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etapa',
            name='setup',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.DeleteModel(
            name='motivoParada',
        ),
    ]
