# Generated by Django 4.1.4 on 2023-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_etapa_controleparado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='tem_acessorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='controleParado',
            field=models.IntegerField(default=0, verbose_name='Total Parado Efetivo'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='parado',
            field=models.IntegerField(default=0, verbose_name='Total Parado Bruto'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='quantidadeParadas',
            field=models.IntegerField(default=0, verbose_name='Quantiadade de Paradas'),
        ),
    ]
